name: Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Run semantic-release in dry-run (--noop)"
        type: choice
        options: ["false", "true"]
        required: false
        default: "false"

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  semantic_release:
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # required for tags history
          fetch-tags: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Set up uv
        uses: astral-sh/setup-uv@v4

      # Optional: install dev deps if release hooks need the environment
      - name: Sync dev dependencies
        run: uv sync --group dev

      - name: Run semantic-release (with optional dry-run)
        env:
          # python-semantic-release reads GH_TOKEN for GitHub operations
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          FLAGS=""
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ "${{ inputs.dry_run }}" = "true" ]; then
            FLAGS="--noop"
            echo "Running semantic-release in dry-run mode (--noop)"
          fi
          uv run semantic-release ${FLAGS} publish
