name: Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Run semantic-release in dry-run (--noop)"
        type: choice
        options: ["false", "true"]
        required: false
        default: "false"

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  semantic_release:
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # required for tags history

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Set up uv
        uses: astral-sh/setup-uv@v4

      # Optional: install dev deps if release hooks need the environment
      - name: Sync dev dependencies
        run: uv sync --group dev

      - name: Bootstrap initial tag if missing
        run: |
          if [ -z "$(git tag -l 'v*')" ]; then
            echo "No release tags found; bootstrapping from pyproject.toml"
            VER=$(python - <<'PY'
            import tomllib, pathlib
            data = tomllib.loads(pathlib.Path('pyproject.toml').read_text(encoding='utf-8'))
            print(data['project']['version'])
            PY
            )
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git tag -a "v${VER}" -m "chore(release): ${VER} (bootstrap)"
            git push origin "v${VER}"
          else
            echo "Existing release tags found; skipping bootstrap"
          fi

      - name: Run semantic-release (with optional dry-run)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          FLAGS=""
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ "${{ inputs.dry_run }}" = "true" ]; then
            FLAGS="--noop"
            echo "Running semantic-release in dry-run mode (--noop)"
          fi
          uv run semantic-release ${FLAGS} publish
